# Yoonhyuck WOO / Purdue University_Computer and Information Technology
# Title: Calculate similarity according to either word2vec or glove
# Professor: Dr. Julia Rayz
 - Reference: https://www.cs.toronto.edu/~lczhang/321/lec/glove_notes.html

In [1]:
import numpy as np
from scipy import spatial
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

In [10]:
embeddings_dict = {}
with open("C:\\Users\\LG\\Desktop\\github\\Purdue-2023-FALL\\GloVe-master\\glove.6B\\glove.6B.300d.txt", 'r',encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector

In [11]:
def find_closest_embeddings(embedding):
    return sorted(embeddings_dict.keys(), key=lambda word: spatial.distance.euclidean(embeddings_dict[word], embedding))

In [15]:
find_closest_embeddings(embeddings_dict['hamster'])[:5]

['hamster', 'hamsters', 'kd94', 'js03', 'kd96']

In [12]:
print(find_closest_embeddings(
    embeddings_dict["twig"] - embeddings_dict["branch"] + embeddings_dict["hand"]
)[:5])

['twig', 'hand', 'cupping', 'fingers', 'paddles']


# Reference: https://www.cs.toronto.edu/~lczhang/321/lec/glove_notes.html

In [2]:
import torch
import torchtext

In [4]:
# The first time you run this will download a ~2.03GB file
glove = torchtext.vocab.GloVe(name="840B", # trained on Common Crawl
                              dim=300)    # embedding size = 50

.vector_cache\glove.840B.300d.zip: 2.18GB [06:58, 5.20MB/s]                                                            
100%|█████████████████████████████████████████████████████████████████████▉| 2196016/2196017 [06:21<00:00, 5755.58it/s]


In [5]:
word = 'mouse'
other = ['seal', 'owl', 'hamster']
for w in other:
    dist = torch.norm(glove[word] - glove[w]) # euclidean distance
    print(w, float(dist))

seal 8.985099792480469
owl 7.963037967681885
hamster 6.431023120880127


In [31]:
torch.cosine_similarity(glove['mouse'].unsqueeze(0),
                        glove['hamster'].unsqueeze(0))

tensor([0.5533])

In [25]:
torch.cosine_similarity(glove['mouse'].unsqueeze(0),
                        glove['owl'].unsqueeze(0))

tensor([0.3426])

In [26]:
torch.cosine_similarity(glove['mouse'].unsqueeze(0),
                        glove['seal'].unsqueeze(0))

tensor([0.1650])

In [27]:
torch.cosine_similarity(glove['hamster'].unsqueeze(0),
                        glove['seal'].unsqueeze(0))

tensor([0.1314])

In [28]:
torch.cosine_similarity(glove['owl'].unsqueeze(0),
                        glove['hamster'].unsqueeze(0))

tensor([0.3626])

In [29]:
torch.cosine_similarity(glove['seal'].unsqueeze(0),
                        glove['owl'].unsqueeze(0))

tensor([0.2472])